name: Generate Snake

on:
  schedule: # jalan otomatis tiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch: # bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Indah135
          outputs: dist/snake.svg

      - name: Upload snake.svg ke branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
